### PR TITLE
Updated CH prefix to SC for tickets

### PR DESCRIPTION
**Pull request by Dmitrev**
Updated the `CH` prefix to `SC` related to issue #12

### CODE REVIEW

**Comment by Dmitrev** [comment]
Not sure why, but the Unit tests don't seem to run.

**Comment by Dmitrev** [comment]
Tests pass locally:

```
$ mocha


  clubhouse module
    story id extraction from release body
      ✓ should find all story ids in well formatted release
      ✓ should find all story ids in poorly formatted release
      ✓ should not match plain number strings
      ✓ should not match other strings beginning in "ch"
      ✓ should find 1 story id in PR Title
      ✓ should find 1 story id in branch name
      ✓ should find 1 story id from duplicates
    adding details to stories
Could not locate story: 27543
      ✓ should return story id for 404 not found
      ✓ should throw for other errors
    updating story descriptions
      ✓ should update a description with content
      ✓ should update a description without content
      ✓ should not update a description that has release info
      ✓ should preserve other properties of story
      ✓ should update descriptions when true
      ✓ should not update descriptions when false
    Adding the end workflow state id to stories
      ✓ should add expected id when end state name is "Completed"
      ✓ should add expected id when end state name is not "Completed"
      ✓ should preserve other properties of story
    Updating stories with the clubhouse api
      ✓ should succeed when returns updated story
      ✓ should error when it returns not updated story


  20 passing (27ms)

Done in 1.85s.
```

**Comment by Dmitrev** [comment]
If anyone wants to tinker with this, I have some docker commands, just clone repo and run this from within the root dir


Install dependencies:
`docker run -v $(pwd):/code -w /code node yarn install`

Run tests:
`docker run -v $(pwd):/code -w /code node yarn test`

Build dist files:
`docker run -v $(pwd):/code -w /code node yarn package`

**Comment by kuritz** [comment]
Thanks @Dmitrev ! Can we do this in a non-breaking way so any users that still have `ch` based ticket ids dont get broken by the update? I think we should allow both `ch` and `sc` to work for a few weeks and then we can deprecate `ch`.

**Comment by Dmitrev** [comment]
@kuritz I think a great suggestion, will do that. 
How do you usually go about testing new updates?

**Comment by kuritz** [comment]
There's a GitHub action that should run the tests. I think there might be a default security setting that prevents it from running on forks. I'll see if I can get that working so you get test runs.

I also have a separate 'mock' repo setup for e2e testing I use prior to releases. There's a link in the badge in the README.

**Comment by Dmitrev** [comment]
@kuritz took me a little while to find some time to update PR, but should be working now for `CH` as well as `SC` formats

**Comment by kuritz** [comment]
This looks great @Dmitrev ! I think I need to update the test trigger to `pull_request` to get them working so I'll just check out your branch manually this time and fix that for the next release.

**Review by kuritz — APPROVED** [review]
Tests are passing and all looks good!

**Comment by kuritz** [comment]
closes #12

**Pull request merged**
